CC_FLAGS = -Wall -pedantic -Wextra -O3 -g -lpthread
CC = gcc

default: all

main:
	$(CC) main.c -o main $(CC_FLAGS)

all: main
clean:
	rm -rf ./*.a ./*.o psearch_normal psearch1a psearch1b psearch1c psearch2a psearch2aslave psearch2b psearch2bslave psearch2c psearch2cslave psearch2d psearch2dslave psearch3